added TC22
teachandlearn999/group_js_for_qas09 pull request #31
Opened 2024-11-18 22:16 UTC by kgold2018

Added Test Case 22: Add to cart from Recommended items

2024-11-18 23:26 UTC, Stavolg commented on cypress/cypress/e2e/AE_Tests.cy.js
> +        cy.visit('http://automationexercise.com');
The visit to the main page has been moved to beforeEach.

2024-11-18 23:27 UTC, Stavolg commented on cypress/cypress/e2e/AE_Tests.cy.js
> +        cy.get('.recommended_items h2.title')
At the last lesson, we decided to use single-line commands. Earlier, I had already fixed all the commands that were written in multiple lines.

2024-11-18 23:27 UTC, Stavolg requested changes
Need Single-Line Commands

2024-11-20 03:45 UTC, DJKommander approved these changes

2024-11-21 20:45 UTC, afaabb approved these changes

2024-11-22 04:07 UTC, Stavolg approved these changes
didn't fix Single-Line Commands

2024-11-22 04:12 UTC, merged